### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by Wulfvenstierna** [domipoppe/Game-Server-Status-Information-API#2]
Used the API to send player count info to a couple of Discord bots for M&B servers, but it went down.

Exempt of the error message:
0|index    | Error: getaddrinfo ENOTFOUND api.dominic-poppe.dev
0|index    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

**Comment by domipoppe** [comment]
Hey,

yeah I changed the host to:

https://api.idiox.io/gameserver_information/v1
